config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }
  devise_for :admin_users, ActiveAdmin::Devise.config

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  ActiveAdmin.routes(self)

  resources :designs, only: :index do
    member do
      get "/existed" ,to: 'design#existed', as: 'existed'
      get "/how_to" ,to: 'design#how_to', as: 'how_to'
    end
  end

  root 'index#index'

  get "/print_order" ,to: 'print#print_order', as: 'print_order'

  get "/print_quotation" ,to: 'print#print_quotation', as: 'print_quotation'

  get "/test" ,to: 'index#test', as: 'test'

  post "/print_art_work" ,to: 'print#print_art_work', as: 'print_art_work'

  get "/order_make_quotation" ,to: 'admin#order_make_quotation', as: 'order_make_quotation'
  get "/order_make_contact" ,to: 'admin#order_make_contact', as: 'order_make_contact'

  get "/orders", to: 'order#index', as: 'order_index'

  get "/test_pdf" ,to: 'print#test_pdf' ,as: 'test_pdf'

  get '/price_calculate_doc', to: "index#price_calculate_doc"
end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :quotations
  belongs_to :admin_user
  belongs_to :user

  has_attached_file :stuff_img,
                    :url => "/:attachment/:id_partition/:style/:basename.:extension",
                    :path => ":rails_root/public/:attachment/:id_partition/:style/:basename.:extension",
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: ""
  validates_attachment_content_type :stuff_img, content_type: /\Aimage\/.*\z/

  def order_name
    "#{self.first_name}"
  end

  def name
    "#{self.id}"
  end

  def json_price_amount_report
    if !self.price_amount_report.nil?
      return JSON.parse(self.price_amount_report)
    else
      return []
    end
  end

  def json_estimate_cost
    if !self.estimate_cost.nil?
      return JSON.parse(self.estimate_cost)
    else
      return []
    end
  end
  def self.enable_access_control
    true
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.where(user: current_user).order("created_at desc")
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
<div class="container ipolo-orders-wrapper">
    <h1> รายการออเดอร์ </h1>
    <% counter = 0 %>
    <% if @orders.count == 0%>
      <p class="order-not-found">
        ไม่พบออเดอร์ <a href="<%= designs_path %>"> ไปหน้าออกแบบ </a>
      </p>
    <% else %>
      <% @orders.each_with_index do |order, index| %>
        <% counter += 1 %>
        <% order.stuff_picker ? stuff = JSON.parse(order.stuff_picker) : stuff = [] %>
        <div class="row order-row">
          <div class="col-md-3">
            <img class="order-img" src="<%= order.stuff_img.url(:medium) %>">
            <table class="table">
                <tbody>
                  <% stuff.each do |item| %>
                    <tr>
                      <td><%= item['stuff_type_name'] %></td>
                      <td><%= item['desc'] %></td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
          </div>
          <div class="col-md-9">
            <h2>
              หมายเลขออเดอร์ #<%= order.id %> <span class="order-created"><%= order.created_at.strftime("วันที่ %m/%d/%Y เวลา %I:%M%p") %></span>
            </h2>
            
            <div class="row">
              <div class="col-md-12">
                <% male = false %>
                <% female = false %>
                <% male_list = [] %>
                <% female_list = [] %>
                <% stuff_price = order.json_estimate_cost() %>
                <% stuff_price.each do |price| %>
                  <% if price['amount'].to_i > 0 %>
                    <% item = {
                      :size => price['size'].split('_')[0],
                      :amount => price['amount'].to_i,
                      :price_per_unit => price['price_per_unit'].to_i
                    } %>
                    <% if price['size'].split('_')[1] == 'male' %>
                      <% male = true %>
                      <% male_list.push(item) %>
                    <% elsif price['size'].split('_')[1] == 'female' %>
                      <% female = true %>
                      <% female_list.push(item) %>
                    <% end %>
                  <% end %>
                <% end %>

                <% if male %>
                  <div class="panel-group" id="accordion-<%= index+counter %>">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <div class="panel-title accordion-toggle" data-toggle="collapse" data-parent="#accordion-<%= index+counter %>" href="#collapseOne-<%= index+counter %>">
                          จำนวนไซส์ ผู้ชาย
                        </div>
                      </div>
                      <div id="collapseOne-<%= index+counter %>" class="panel-collapse collapse">
                        <div class="panel-body">                
                          <table class="table">
                            <thead>
                              <tr>
                                <th>ไซส์</th>
                                <th>จำนวน</th>
                              </tr>
                            </thead>
                            <tbody>
                              <% male_list.each do |item| %>
                                <tr>
                                  <td><%= item[:size] %></td>
                                  <td><%= item[:amount] %></td>
                                </tr>
                              <% end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <% counter += 1 %>
                <% if female %>
                  <div class="panel-group" id="accordion-<%= index+counter %>">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <div class="panel-title accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne-<%= index+counter %>">
                            จำนวนไซส์ ผู้หญิง
                        </div>
                      </div>
                      <div id="collapseOne-<%= index+counter %>" class="panel-collapse collapse">
                        <div class="panel-body">                
                          <table class="table">
                            <thead>
                              <tr>
                                <th>ไซส์</th>
                                <th>จำนวน</th>
                              </tr>
                            </thead>
                            <tbody>
                              <% female_list.each do |item| %>
                                <tr>
                                  <td><%= item[:size] %></td>
                                  <td><%= item[:amount] %></td>
                                </tr>
                              <% end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-9">
                <div class="order-price">ราคา <%= number_to_currency(order.total_price, unit: "") %> บาท</div>
              </div>
              <div class="col-md-3">
                <% if order.status == "no contact"%>
                  <button class="btn ipolo-btn order-btn" data-order-id="<%= order.id %>" data-price="<%= order.total_price %>">แจ้งโอน</button>
                <% elsif order.status == "contact" || order.status == "pending" %>
                  <div class="order-status pending"> กำลังตรวจสอบ </div>
                  <button class="btn ipolo-btn order-btn" data-order-id="<%= order.id %>" data-price="<%= order.total_price %>">แจ้งโอน</button>
                <% elsif order.status == "quotation" %>
                  <div class="order-status quotation"> ชำระเงินแล้ว </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

</div>

<%= render "designs/modal" %>